### ISSUE TITLE
The C# Bitmap class has been flagged by Windows Defender

### ISSUE THREAD

**Issue by UIWP0** [HannesCr4ft16/ImgBWObfus#1]
Hi.bro

C# Bitmap class is marked as malicious by Windows Defender, how can I bypass it?

![image](https://user-images.githubusercontent.com/32759429/230835183-4a1e2332-bfe7-4d45-ae07-59d486870a98.png)

![image](https://user-images.githubusercontent.com/32759429/230834931-257df4cd-4a43-4737-afdb-c2c9344fb692.png)

Have a great day!

**Comment by HannesAuer** [comment]
Normally the Bitmap Class should not be flagged by Windows Defender. Make sure that the correct class is used and the code is implemented correctly. This might help: https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?view=dotnet-plat-ext-7.0

Otherwise try:
- Update Windows Defender: Make sure that Windows Defender is up to date with the latest virus definitions and security updates.

- Add an exclusion: Add an exclusion for your C# Bitmap class in Windows Defender. This will prevent Windows Defender from scanning and flagging your code.

- Scan your code with other antivirus software: Run a scan of your code with other antivirus software to check if it is actually infected with a virus. If the other antivirus software does not detect any issues, it is likely that Windows Defender is flagging your code due to a false positive.

- Contact Microsoft: If none of the above steps resolve the issue, you can contact Microsoft for further assistance. They may be able to provide more information on why your code is being flagged as a virus and how to resolve the issue.
